<?php
use Drupal\Core\Database\Database;

/**
 * Implements hook_ENTITY_presave().
 */

// function views_custom_file_presave(Drupal\Core\Entity\EntityInterface $entity) {
//   if ($entity->getEntityTypeId() === 'file') {
//     $fid = $entity->id();
 
    
//     if ($fid) {
//       // Fetch count from secondary database.
//       $file_count = views_custom_get_file_count_from_secondary_db($fid);
    
//       if ($file_count !== NULL) {  
//         // Update the primary database table.
//         views_custom_update_file_count($fid, $file_count);
//       }
//     }
//   }
// }

/**
 * Fetch file count from the secondary database.
 */
function views_custom_get_file_count_from_secondary_db($fid) {
  try {
    $database = Database::getConnection('default', 'migrate');    
    $query = $database->select('download_count', 't')
      ->condition('fid', $fid)
      ->countQuery()
      ->execute();   
    return (int) $query->fetchField();  

  }
  catch (Exception $e) {
    \Drupal::logger('views_custom')->error('Error fetching file count: @message', ['@message' => $e->getMessage()]);
    return NULL;
  }
}
function views_custom_update_file_count($fid, $file_count) {
  if ($file_count === 0) {
    // \Drupal::logger('views_custom')->notice("Skipping file ID $fid as count is zero.");
    return; // Skip this entry but continue processing others
  }

  if (\Drupal::moduleHandler()->moduleExists('file_download_counter')) {
    $count_downloads = \Drupal::config('file_download_counter.settings')->get('count_downloads');
    if ($count_downloads) {
      \Drupal::database()->merge('file_download_counter')
        ->key('fid', $fid)
        ->fields([
          'daycount' => 1,
          'totalcount' => $file_count,
          'timestamp' => \Drupal::time()->getRequestTime(),
        ])
        ->expression('daycount', 'daycount + 1')
        ->expression('totalcount', 'totalcount + ' . $file_count)
        ->execute();
    }
  }
}


